// src/lib/quotes.ts

// An array of quotes from Thich Nhat Hanh
const thichNhatHanhQuotes = [
    { quote: "Life is available only in the present moment.", author: "Thich Nhat Hanh" },
    { quote: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
    { quote: "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.", author: "Thich Nhat Hanh" },
    { quote: "Letting go gives us freedom, and freedom is the only condition for happiness.", author: "Thich Nhat Hanh" },
    { quote: "Smile, breathe and go slowly.", author: "Thich Nhat Hanh" },
    { quote: "The true miracle is not walking on water or walking in air, but simply walking on this earth.", author: "Thich Nhat Hanh" },
    { quote: "Walk as if you are kissing the Earth with your feet.", author: "Thich Nhat Hanh" },
    { quote: "Hope is important because it can make the present moment less difficult to bear.", author: "Thich Nhat Hanh" },
    { quote: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
    { quote: "Waking up this morning, I smile. Twenty-four brand new hours are before me. I vow to live fully in each moment.", author: "Thich Nhat Hanh" },
    { quote: "Many people think excitement is happiness... But when you are excited you are not peaceful. True happiness is based on peace.", author: "Thich Nhat Hanh" },
    { quote: "The seed of suffering in you may be strong, but don't wait until you have no more suffering before allowing yourself to be happy.", author: "Thich Nhat Hanh" },
    { quote: "Breathing in, I calm body and mind. Breathing out, I smile.", author: "Thich Nhat Hanh" },
    { quote: "The foundation of happiness is mindfulness. The basic condition for being happy is our consciousness of being happy.", author: "Thich Nhat Hanh" },
    { quote: "Mindfulness practice means that we commit fully in each moment to be present.", author: "Thich Nhat Hanh" },
    { quote: "We really have to understand the person we want to love. If our love is only a will to possess, it is not love.", author: "Thich Nhat Hanh" },
    { quote: "The mind can go in a thousand directions, but on this beautiful path, I walk in peace.", author: "Thich Nhat Hanh" },
    { quote: "If in our daily lives we can smile, if we can be peaceful and happy, not only we, but everyone will profit from it.", author: "Thich Nhat Hanh" },
    { quote: "When another person makes you suffer, it is because he suffers deeply within himself... He does not need punishment; he needs help.", author: "Thich Nhat Hanh" },
    { quote: "Every day we are engaged in a miracle which we don't even recognize: a blue sky, white clouds, green leaves... All is a miracle.", author: "Thich Nhat Hanh" },
];

// An array of quotes from the Dalai Lama
const dalaiLamaQuotes = [
    { quote: "If you want others to be happy, practice compassion. If you want to be happy, practice compassion.", author: "Dalai Lama" },
    { quote: "Love and compassion are necessities, not luxuries. Without them, humanity cannot survive.", author: "Dalai Lama" },
    { quote: "The goal is not to be better than the other man, but your previous self.", author: "Dalai Lama" },
    { quote: "Remember that sometimes not getting what you want is a wonderful stroke of luck.", author: "Dalai Lama" },
    { quote: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.", author: "Dalai Lama" },
    { quote: "We can never obtain peace in the outer world until we make peace with ourselves.", author: "Dalai Lama" },
    { quote: "Choose to be optimistic, it feels better.", author: "Dalai Lama" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "In the practice of tolerance, one's enemy is the best teacher.", author: "Dalai Lama" },
    { quote: "A lack of transparency results in distrust and a deep sense of insecurity.", author: "Dalai Lama" },
    { quote: "Calm mind brings inner strength and self-confidence, so that's very important for good health.", author: "Dalai Lama" },
    { quote: "Give the ones you love wings to fly, roots to come back, and reasons to stay.", author: "Dalai Lama" },
    { quote: "Old friends pass away, new friends appear. It is just like the days. An old day passes, a new day arrives.", author: "Dalai Lama" },
    { quote: "Take into account that great love and great achievements involve great risk.", author: "Dalai Lama" },
    { quote: "My religion is very simple. My religion is kindness.", author: "Dalai Lama" },
    { quote: "Once a year, go someplace you've never been before.", author: "Dalai Lama" },
    { quote: "A disciplined mind leads to happiness, and an undisciplined mind leads to suffering.", author: "Dalai Lama" },
    { quote: "The way to change others' minds is with affection and not anger.", author: "Dalai Lama" },
];

// An array of assorted mindfulness quotes
const assortedMindfulnessQuotes = [
    { quote: "The best way to capture moments is to pay attention.", author: "Jon Kabat-Zinn" },
    { quote: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn" },
    { quote: "The little moments? They aren't little.", author: "Jon Kabat-Zinn" },
    { quote: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
    { quote: "Peace comes from within. Do not seek it without.", author: "Buddha" },
    { quote: "Nothing can harm you as much as your own thoughts unguarded.", author: "Buddha" },
    { quote: "Wherever you are, be there totally.", author: "Eckhart Tolle" },
    { quote: "In today's rush, we all think too much, seek too much, want too much, and forget about the joy of just being.", author: "Eckhart Tolle" },
    { quote: "You have a treasure within you that is infinitely greater than anything the world can offer.", author: "Eckhart Tolle" },
    { quote: "Mindfulness isn't difficult, we just need to remember to do it.", author: "Sharon Salzberg" },
    { quote: "That's life: starting over, one breath at a time.", author: "Sharon Salzberg" },
    { quote: "Meditation is the only intentional, systematic human activity which at bottom is about not trying to improve yourself or get anywhere else, but simply to realize where you already are.", author: "Jon Kabat-Zinn" },
    { quote: "When we get too caught up in the busyness of the world, we lose connection with one another – and ourselves.", author: "Jack Kornfield" },
    { quote: "Mindfulness does not reject experience. It lets experience be the teacher.", author: "Jack Kornfield" },
    { quote: "The things that matter most in our lives are not fantastic or grand. They are moments when we touch one another.", author: "Jack Kornfield" },
    { quote: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
    { quote: "There is something wonderfully bold and liberating about saying yes to our entire imperfect and messy life.", author: "Tara Brach" },
    { quote: "What would it be like if I could accept life—accept this moment—exactly as it is?", author: "Tara Brach" },
    { quote: "Worrying is stupid. It's like walking around with an umbrella waiting for it to rain.", author: "Wiz Khalifa" },
    { quote: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
    { quote: "The feeling that any task is a nuisance will soon disappear if it is done in mindfulness.", author: "Thich Nhat Hanh" },
    { quote: "Between stimulus and response there is a space. In that space is our power to choose our response.", author: "Victor Frankl" },
    { quote: "To see a world in a grain of sand and heaven in a wild flower, Hold infinity in the palm of your hand and eternity in an hour.", author: "William Blake" },
    { quote: "If you clean the floor with love, you have given the world an invisible painting.", author: "Osho" },
    { quote: "The most fundamental aggression to ourselves... is to remain ignorant by not having the courage and the respect to look at ourselves honestly and gently.", author: "Pema Chödrön" },
    { quote: "Don't let life harden your heart.", author: "Pema Chödrön" },
    { quote: "Nothing ever goes away until it has taught us what we need to know.", author: "Pema Chödrön" },
    { quote: "A mind is like a parachute. It doesn't work if it isn't open.", author: "Frank Zappa" },
    { quote: "Be happy in the moment. That is enough.", author: "Mother Teresa" },
    { quote: "The perfect moment is this one.", author: "Jon Kabat-Zinn" },
    { quote: "When you're quiet, everything settles on the floor of your mind like sediment in undisturbed still water.", author: "Megan Monahan" },
    { quote: "Ask yourself: Where am I? Answer: Here. Ask yourself: What time is it? Answer: Now. Say it until you can hear it.", author: "Ram Dass" },
    { quote: "There is nothing more important to true growth than realizing that you are not the voice of the mind—you are the one who hears it.", author: "Michael A. Singer" },
    { quote: "Meditation means dissolving the invisible walls that unawareness has built.", author: "Sadhguru" },
    { quote: "Looking at beauty in the world is the first step of purifying the mind.", author: "Amit Ray" },
    { quote: "If you want to conquer the anxiety of life, live in the moment, live in the breath.", author: "Amit Ray" },
    { quote: "Life is a dance. Mindfulness is witnessing that dance.", author: "Amit Ray" },
    { quote: "The real meditation practice is how you live your life from moment to moment.", author: "Jon Kabat-Zinn" },
    { quote: "Altogether, the idea of meditation is not to create states of ecstasy or absorption, but to experience being.", author: "Chögyam Trungpa" },
    { quote: "This is the real secret of life — to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.", author: "Alan Watts" },
    { quote: "You only lose what you cling to.", author: "Buddha" },
    { quote: "The art of peaceful living comes down to living compassionately & wisely.", author: "Allan Lokos" },
    { quote: "Don't believe everything you think. Thoughts are just that - thoughts.", author: "Allan Lokos" },
    { quote: "The stiller you are the calmer life is.", author: "Rasheed Ogunlaru" },
    { quote: "Step outside for a while—calm your mind. It is better to hug a tree than to bang your head against a wall continually.", author: "Rasheed Ogunlaru" },
    { quote: "Our life is shaped by our mind, for we become what we think.", author: "Buddha" },
    { quote: "With awareness, we can make conscious choices instead of letting our habitual thoughts and patterns run the show.", author: "Tamara Levitt" },
    { quote: "Mindfulness is a simple practice, but not an easy one... but you are worth doing hard things.", author: "Nicole Davis" },
    { quote: "Be where you are, otherwise, you will miss your life.", author: "Buddha" },
    { quote: "When we allow ourselves to embrace the moment, we allow ourselves to live.", author: "Lisa Bien" }
];


// Combine all arrays into one master list and export it
export const allQuotes = [
    ...thichNhatHanhQuotes,
    ...dalaiLamaQuotes,
    ...assortedMindfulnessQuotes,
];